[package]
name = "workflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cloudagent-python = {path = "../cloudagent-python"}
agent = {path = "../agent"}
async-trait = "0.1.51"
log = "0.4.14"
