[package]
name = "automations"
version = "0.0.0"
edition = "2021"

[dependencies]
cloudagent-python = { path = "../cloudagent-python" }
colored = "2.0.0"
agent = { path = "../agent" }
async-trait = "0.1.51"
