name: build-and-release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: macos-latest
    strategy:
      matrix:
        architecture: [aarch64-apple-darwin, x86_64-apple-darwin, x86_64-unknown-linux-musl, x86_64-pc-windows-gnu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{matrix.architecture}} --all-features --package cli
      - run: ls -R
      - name: Save library
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.architecture}}
          # TODO: tar.gz
          path: target/${{ matrix.architecture }}/release/aries-cli
